sudo: false
language: node_js
cache:
  directories:
    - ~/.yarn-cache
notifications:
  email: false
node_js:
  - '6'
before_install:
  - npm i -g codecov yarn
install:
  - yarn
script:
  - yarn run cover
  - codecov
after_success:
  - yarn run semantic-release
branches:
  except:
    - /^v\d+\.\d+\.\d+$/
